### PR TITLE
Updated DSA files

### PR DESCRIPTION
**Pull request by Parmesh119**
**@anirban-oss, I have updated the files and now you can see them...
If some changes that I have to make please let me know...🙏**

### CODE REVIEW

**Comment by anirban-oss** [comment]
This is still deleting stuff

1. Revert back to the initial repo
2. Make a folder by your name
3. Add the files
4. Don't delete any files

**Comment by Parmesh119** [comment]
ok.
Please give me some time because my college is going on...

**Comment by anirban-oss** [comment]
Please do not hurry, take your time, its okay, no worries.
Learn the basics, forking, pull, push and branching and then making a PR

**Comment by Parmesh119** [comment]
ok

**Pull request closed without merging**
